name: ESP32 Arduino Release

on:
  workflow_dispatch:

env:
  IDF_BRANCH: release/v4.4
  IDF_COMMIT: tags/v4.4.8
  ARDUINO_BRANCH: release/v2.x
  ARDUINO_COMMIT: 1f038677eb2eaf5e9ca6b6074486803c15468bed

jobs:
  build:
    name: Build Libs
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.out.outputs.tag }}
      release_name: ${{ steps.out.outputs.release_name }}
    steps:
    - uses: actions/checkout@v6
    - name: Compute release name
      id: compute
      run: |
          ARDUINO_BRANCH_SUFFIX="${ARDUINO_BRANCH#release/}"
          ARDUINO_SHORT_SHA="${ARDUINO_COMMIT:0:7}"
          ARDUINO_VERSION="${ARDUINO_BRANCH_SUFFIX}-${ARDUINO_SHORT_SHA}"
          SHORT_SHA=$(git rev-parse --short HEAD)
          REPO="${{ github.event.repository.name }}"

          TAG="${ARDUINO_VERSION}-${SHORT_SHA}"
          RELEASE_NAME="${REPO}-${TAG}"

          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          echo "release_name=${RELEASE_NAME}" >> "$GITHUB_OUTPUT"
    - name: Install dependencies
      run: bash ./tools/prepare-ci.sh
    - name: Build Libs
      run: bash ./build.sh -I $IDF_BRANCH -i $IDF_COMMIT -A $ARDUINO_BRANCH -a $ARDUINO_COMMIT
    - name: Upload archive with libs
      uses: actions/upload-artifact@v4
      with:
        name: libs
        path: out
    - name: Upload archive with Arduino
      uses: actions/upload-artifact@v4
      with:
        name: arduino
        path: components/arduino
    - name: Pass release name to next job
      id: out
      run: |
        echo "tag=${{ steps.compute.outputs.tag }}" >> "$GITHUB_OUTPUT"
        echo "release_name=${{ steps.compute.outputs.release_name }}" >> "$GITHUB_OUTPUT"
  release:
    runs-on: ubuntu-latest
    needs: build
    name: Release Package
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
      - name: Compute package name
        id: compute
        run: |
          PACKAGE_NAME="framework-arduinoespressif32-${{ needs.build.outputs.tag }}.tar.gz"

          echo "package_name=${PACKAGE_NAME}" >> "$GITHUB_OUTPUT"
      - name: Build package
        run: |
          find
          cp -a libs/. arduino/
          rm -rf arduino/.git
          tar cvfz ${{ steps.compute.outputs.package_name }} -C arduino/ .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          name: ${{ needs.build.outputs.release_name }}
          files: |
            ${{ steps.compute.outputs.package_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
